In [ ]:
import numpy as np

In [ ]:
#creating an array of type int and length 10
print(np.zeros(10, dtype='int'))#creating array with zeros length 10
print(np.ones((3,5), dtype=float))# creating array with flaoting point values
print(np.full((3,5),1.23))#creating array with pre-defined values
print(np.arange(0, 20, 2))#create an array with a set sequence
print(np.linspace(0, 1, 5)) #create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
print(np.eye(3))#create an identity matrix

In [ ]:
#accessing array elements
x1 = np.array([4, 3, 2, 13, 8, 4])
print(x1)
print(x1[0], x1[5])
print(x1[-1], x1[-6])
x2=np.array([[3, 7, 5, 5],
      [0, 1, 5, 9],
      [3, 0, 5, 0]])
print(x2)
print(x2[2,3])
print(x2[2,-2])


[ 4  3  2 13  8  4]
4 4
4 4
[[3 7 5 5]
 [0 1 5 9]
 [3 0 5 0]]
0
5


In [ ]:
#array slicing single dimension
x = np.arange(10)
print(x)
print(x[:5])#from start to 4th position
print(x[4:])#from 4th position to end
print(x[4:7])#from 4th position to 6
print(x[: : 2])#return elements at even place
print(x[: : -1])#reverse the array
print(x[1: : 2])#return elements from index 1 position step by two

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[4 5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]
[1 3 5 7 9]


In [ ]:
#array slicining in multidimensional array
print(x2)
print(x2.shape)
print(x2[0:2])
print(x2[0:2,1:3])
print(x2[2])
print(x2[:,2])

[[3 7 5 5]
 [0 1 5 9]
 [3 0 5 0]]
(3, 4)
[[3 7 5 5]
 [0 1 5 9]]
[[7 5]
 [1 5]
 [0 5]]
[3 0 5 0]
[5 5 5]


In [ ]:
# creating 3D array in numpy
x3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(x3)
print(x3.shape)
print(x3[0,0,1])

In [ ]:
#Splitting and concatenation of arrays
#concatenation
x1=np.arange(0,10,2)
x2=np.arange(10,20,2)
print(x1,x2)
#x3=np.concatenate([x1, x2], axis=0)
#x3=np.stack([x1,x2], axis=0)
x3=np.vstack([x1,x2])
print(x3)




[0 2 4 6 8] [10 12 14 16 18]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [ ]:
#2D array concatenta
x1=np.array([[1,2,3,4],[5,6,7,8]])
x2=np.array([[9,10,11,12],[13,14,15,16]])
#print(x1,x2)
x3=np.concatenate([x1, x2],axis=0)
x3=np.hstack([x1, x2])
x3=np.vstack([x1, x2])
print(x3, x3.shape)
np.hsplit(x3,[2])



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] (4, 4)


[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [ ]:
#array Splitting
x1=np.arange(0,15,2)
print(x1)
#x2=np.split(x1,[3])#spilt before index 2 and 4
x2=np.array_split(x1,3)#split into array of size 3
print(x2)


[ 0  2  4  6  8 10 12 14]
[array([0, 2, 4]), array([ 6,  8, 10]), array([12, 14])]


In [ ]:
#array reshaping
print(x3)
r,c=x3.shape
print(r,c)
x4=x3.reshape(-1,2)
print(x4)
#x4=x3.reshape(-1,2, order="F")#replace col by col
x4=np.ravel(x3, order="C")
x5=np.ravel
print(x4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
4 4
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
[ 1  5  9 13  2  6 10 14  3  7 11 15  4  8 12 16]


In [ ]:
a1 = np.arange(1, 13).reshape(3, -1)  # 3_4
a2 = np.arange(13, 25).reshape(3, -1)  # 3_4
a3=np.dstack([a1,a2])
print(a3,a3.shape)
a4=a3.reshape(2,2,-1)
print(a4, a4.shape)

[[[ 1 13]
  [ 2 14]
  [ 3 15]
  [ 4 16]]

 [[ 5 17]
  [ 6 18]
  [ 7 19]
  [ 8 20]]

 [[ 9 21]
  [10 22]
  [11 23]
  [12 24]]] (3, 4, 2)
[[[ 1 13  2 14  3 15]
  [ 4 16  5 17  6 18]]

 [[ 7 19  8 20  9 21]
  [10 22 11 23 12 24]]] (2, 2, 6)


In [ ]:
#arithmetric operation on matrix
A=np.array([[1,2,3,4],[5,6,7,8]])
A,B=np.vsplit(A,[1])
A=A.reshape(2,-1)
B=B.reshape(2,-1)
print(A)
print(B)
#  Addition of a scaler
print ("Addition of two matrices: ")
print (np.add(A,2))#A+B
#  add()is used to add matrices
print ("Addition of two matrices: ")
print (np.add(A,B))#A+B
# subtract()is used to subtract matrices
print ("Subtraction of two matrices : ")
print (np.subtract(A,B))#A-B
# divide()is used to divide matrices
print ("Matrix Division : ")
print (np.divide(A,B))
print ("Multiplication of two matrices: ")
print (np.multiply(A,B))#A*B
print ("The product of two matrices : ")
print (np.dot(A,B))
print ("square root is : ")
print (np.sqrt(A))#A**2
print ("The summation of elements : ")
print (np.sum(A))
print ("The column wise summation  : ")
print (np.sum(A,axis=0))
print ("The row wise summation: ")
print (np.sum(A,axis=1))
# using "T" to transpose the matrix
print ("Matrix transposition : ")
print (A.T)
#moving axis (matrix, source, desination)
print(np.moveaxis(A,0,1 ))
print(A.diagonal())

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Addition of two matrices: 
[[3 4]
 [5 6]]
Addition of two matrices: 
[[ 6  8]
 [10 12]]
Subtraction of two matrices : 
[[-4 -4]
 [-4 -4]]
Matrix Division : 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
Multiplication of two matrices: 
[[ 5 12]
 [21 32]]
The product of two matrices : 
[[19 22]
 [43 50]]
square root is : 
[[1.         1.41421356]
 [1.73205081 2.        ]]
The summation of elements : 
10
The column wise summation  : 
[4 6]
The row wise summation: 
[3 7]
Matrix transposition : 
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[1 4]


In [ ]:
"""
print(A+2)
print(A*2)
print(A**2)
print(A+B)
print(A@B)
print(A*B)
"""



TypeError: ignored

In [ ]:
print(A)
print(A.min())
print(A.max())
print(A.mean())
print(np.std(A))
print(A.min(axis=1))
print(A.max(axis=1))
print(A.mean(axis=1))


[[1 2]
 [3 4]]
1
4
2.5
1.118033988749895
[1 3]
[2 4]
[1.5 3.5]


In [ ]:
A=np.array([1,1,2,3,1,2,3,4,5,6,3,4,4,5,7,6,8,9,1,4,8])
print(np.unique(A))
uniqueValues, indicesList, frequency = np.unique(A, return_index=True,return_counts=True)
print(uniqueValues, indicesList, frequency)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9] [ 0  2  3  7  8  9 14 16 17] [4 2 3 4 2 2 1 2 1]


In [ ]:
A=np.array([[1, 2,1, 3], [4, 3, 2, 1],  [2,1, 1,3], [5,1, 5, 2]])
print(A)
#B=list(set(A.ravel()))
print(np.unique(A))
#print(B)
uniqueValues, indicesList, frequency = np.unique(A, return_index=True,return_counts=True)
print(uniqueValues, indicesList, frequency)
UniqueList=list(zip(uniqueValues, indicesList, frequency))
print(UniqueList)

[[1 2 1 3]
 [4 3 2 1]
 [2 1 1 3]
 [5 1 5 2]]
[1 2 3 4 5]
[1 2 3 4 5] [ 0  1  3  4 12] [6 4 3 1 2]
[(1, 0, 6), (2, 1, 4), (3, 3, 3), (4, 4, 1), (5, 12, 2)]
[[False False False False]
 [ True False False False]
 [False False False False]
 [ True False  True False]]
