Singular Value Decomposition

In [2]:
#to mount the googledrive 
from google.colab import drive
drive.mount('/content/Drive')

Mounted at /content/Drive


In [3]:
import numpy as np
from numpy.linalg import * #linearalgebra

In [18]:

A = np.array([[4,4],[-3,3]])
X = A@A.T
Y = A.T@A

In [19]:
eigVal,eigVal = eig(X)
U = eigVec
print(U)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [13]:
eigVal,eigVec =eig(Y)
V = eigVec
print(V)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [16]:
#findingSigma

sigma = np.diag(eigVal**0.5).round()
print('Sigma',sigma)


Sigma [[6. 0.]
 [0. 4.]]
[[5. 1.]
 [1. 5.]]


In [20]:
B = U@sigma@V.T
print(B)

[[5. 1.]
 [1. 5.]]
